const actionTypes = {
  SET_ALERT: "SET_ALERT",
  LOGIN_USER: "LOGIN_USER",
  LOGOUT_USER: "LOGOUT_USER",
  LOGIN_USER_ERROR: "LOGIN_USER_ERROR",
  LOGOUT_USER_ERROR: "LOGOUT_USER_ERROR",
  GET_PROFILE: "GET_PROFILE",
  EDIT_PROFILE: "EDIT_PROFILE",
  GET_DEMO: "GET_DEMO",
  ADD_DEMO: "ADD_DEMO",
  EDIT_DEMO: "EDIT_DEMO",
  DELETE_DEMO: "DELETE_DEMO",
  GET_EXP: "GET_EXP",
};

export default actionTypes;
