const actionTypes = {
  LOGIN_USER: "LOGIN_USER",
  LOGOUT_USER: "LOGOUT_USER",
  LOGIN_USER_ERROR: "LOGIN_USER_ERROR",
  LOGOUT_USER_ERROR: "LOGOUT_USER_ERROR",
  GET_PROFILE: "GET_PROFILE",
  EDIT_PROFILE: "EDIT_PROFILE",
  GET_DEMO: "GET_DEMO",
  ADD_DEMO: "ADD_DEMO",
};

export default actionTypes;
