const actionTypes = {
  LOGIN_USER: "LOGIN_USER",
  LOGOUT_USER: "LOGOUT_USER",
  LOGIN_USER_ERROR: "LOGIN_USER_ERROR",
  LOGOUT_USER_ERROR: "LOGOUT_USER_ERROR",
  GET_PROFILE: "GET_PROFILE",
  ADD_SOCIAL_LINK: "ADD_SOCIAL_LINK",
};

export default actionTypes;
